name: Build SDK static musl

on:
  push:
  pull_request:
  workflow_call:

jobs:   
  sdk-2020:
    runs-on: ubuntu-22.04
    env:
      FORCE_UNSAFE_CONFIGURE: 1
    steps:
    - uses: actions/checkout@v3
    - name: build SDK static
      run: make sdk
      
    - uses: actions/upload-artifact@v3
      with:
        name: SDK (static-musl)
        path: ${{ inputs.submodule || '.' }}/output/images/arm-buildroot-linux-musleabi_sdk-buildroot.tar.gz
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn` 
